trigger:
  - main  # or your default branch

pool:
  name: Default  # or your custom self-hosted agent pool name

steps:
  - task: UseJava@1
    inputs:
      versionSpec: '11'  # or 17 based on your project
      jdkArchitecture: 'x64'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-Xmx1024m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'  # or 17
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
